export default [
  {
    id: 1001,
    pname: "Samsung Galaxy j7",
    pimg: "img1.jpeg",
    color: "color: red",
    price: "₹70000",
    desciption: "Ram 4Gb Rom 128 89mpx camara  dual sim",
  },
  {
    id: 1002,
    pname: "Redmi Note 10 pro",
    pimg: "img2.jpeg",
    color: "color: blue",
    price: "₹60000",
    desciption: "Ram 2Gb Rom 16Gb 64mpx camara  dual sim",
  },
  {
    id: 1003,
    pname: "I phone 15 promax",
    pimg: "img3.jpeg",
    color: "color: black",
    price: "₹190000",
    desciption: "Ram 6Gb Rom 256 105mpx camara  dual sim",
  },
  {
    id: 1004,
    pname: "Nokia",
    pimg: "img4.jpeg",
    color: "color: green",
    price: "₹30000",
    desciption: "Ram 4Gb Rom 232Gb 90mpx camara  dual sim",
  },
  {
    id: 1005,
    pname: "i phone 16 pro max",
    pimg: "img5.jpeg",
    color: "color: Pink",
    price: "₹190000",
    desciption: "Ram 16Gb Rom 512Gb 90mpx camara dual sim",
  },
  {
    id: 1006,
    pname: "Samsung pro max",
    pimg: "img6.jpeg",
    color: "color: Black",
    price: "₹175000",
    desciption: "Ram 8Gb Rom 512Gb 90mpx camara dual sim",
  },
  {
    id: 1007,
    pname: "Redmi 30 pro max",
    pimg: "img7.jpeg",
    color: "color: Sky blue",
    price: "₹70000",
    desciption: "Ram 16Gb Rom 128Gb 90mpx camara dual sim",
  },
  {
    id: 1008,
    pname: "Samsung galaxy ultra pro ",
    pimg: "img8.jpeg",
    color: "color: Gray",
    price: "₹200000",
    desciption: "Ram 16Gb Rom 1024Gb 90mpx camara  dual sim",
  },
];
